"""transaction

Revision ID: 1057d272b03a
Revises: ab652a1eb17e
Create Date: 2023-11-05 09:53:06.005124

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1057d272b03a"
down_revision: Union[str, None] = "ab652a1eb17e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "COMPLETED", "REJECTED", name="transactionstatus"),
            nullable=True,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "operation_type",
            sa.Enum("BUY", "SELL", name="exchangeoperationtype"),
            nullable=True,
        ),
        sa.Column(
            "from_currency",
            sa.Enum("BTC", "USDT", "ETH", "BUSD", "DAI", name="cryptocurrencies"),
            nullable=True,
        ),
        sa.Column(
            "to_currency",
            sa.Enum("BTC", "USDT", "ETH", "BUSD", "DAI", name="cryptocurrencies"),
            nullable=True,
        ),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    # ### end Alembic commands ###
